### ISSUE TITLE
add OA property/ies for event output

### ISSUE THREAD

**Issue by StroemPhi** [StroemPhi/ConfIDent-schema#3]
We want to be able to find out quickly in ConfIDent if the proceedings/conference papers are open access.

**Comment by hauschke** [comment]
Boolean might not be sufficient to capture OA. It might be useful to use at least a range of OA options (like gold OA, green OA) if we want to enable the use case "I want to publish OA in conference proceedings".

**Comment by StroemPhi** [comment]
@hauschke ok, but then we need a clear definition source for the various OA models. Should this be DOAJ, Unpaywall or ...? Should APCs then also be in there already?

**Comment by StroemPhi** [comment]
The more I think about this, isn't this about the things we would love to get from TIB's OpenPublishing Service?

**Comment by hauschke** [comment]
Would be useful, but complicated, too. We discussed OA modeling in a different context last week. @tawahle or @tullney could maybe help here.

**Comment by StroemPhi** [comment]
I was thinking more in terms of looking at its schema and adapting the properties we need and for which we cold get the actual data from its API. I was thinking, we would have the PID of the journal or series source in which the proceedings/papers are published and we take this to query the TIB OpenPublishing service API to get the fields we need.

**Comment by tullney** [comment]
I would strongly recommend against building your own oa status database. Much work, many errors. If you want to check the open access status of a particular work, use Unpaywall and maybe use a customized mapping of their results to whatever you want to see in your project.

**Comment by tullney** [comment]
Also, I do not see the connection to TIB Open Publishing. Are you talking about something else? If you want to see characteristics of a particular journal, we use DOAJ metadata at https://projects.tib.eu/bison, but as you know that's only for open access journals, so no subscription/hybrid journals and no proceedings.

**Comment by StroemPhi** [comment]
Good points @tullney thanks! And this is why I had only a boolean in mind at first, as getting this info will be really hard, looking at the limitations of DOAJ and Unpaywall.

**Comment by StroemPhi** [comment]
And your right @tullney I mixed something up wrt TIB OpenPublishing. Though we probably want to have some kind of links to it to find out e.g. that an event's proceedings are published in [Open Conference Proceedings](https://www.tib-op.org/ojs/index.php/ocp/index).
